### ISSUE TITLE
Akamai protection: set the cookie in the first child HLS playlist request

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgcontentprotection-apple#1]
### Issue type

Improvement request

### Description of the problem

The first request to Akamai gives a session cookie in the response. All next requests use it.

When created the tokenize URL in the code before set it to `AVPlayer`, the master HLS playlist request gives the cookie and the first child playlist request uses it.

With the current Akamai resource loader delegate implementation, compatible with iOS 9 and iOS 10, the tokenize URL and the master HLS playlist are load in the delegate. `loadingRequest.response = response;` doesn't nothing to `AVURLAsset` and the first child playlist request has no cookie.

It seems that this request is not supported by `AVFoundation`, [regarding this answer](https://stackoverflow.com/a/50276393).

- The redirect option @defagos had first works only on iOS 11.
- Apple engineer proposition with local proxy are not was we want.
- We could try to modify all schemes in playlists to set the cookie in each requests and redirect. Look the [AVARLDelegateDemo](https://developer.apple.com/library/archive/samplecode/sc1791/Introduction/Intro.html) Apple example.

### Environment information

* Library version: 0.1
* iOS version: All
* Device: All

### Reproducibility

In the demo application.

Always reproducible.

### Steps to reproduce

1. Play in the _Vanilla_ section, _unprotected Akamai stream_.
2. Play the _Akamai token support_ section, _unprotected Akamai stream_.

Here is a [Charles proxy capture](https://github.com/SRGSSR/srgcontentprotection-ios/files/2233164/Load.HLS.playlist.manually.or.not.chls.zip).

**Comment by defagos** [comment]
With 3.0.1 the redirect approach is applied on iOS 11+, see issue #6.
