### ISSUE TITLE
1st, 2nd and 3rd Apple TV generations don't play Akamai token protected streams

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgcontentprotection-apple#7]
### Issue type

Incorrect behavior

### Description of the problem

iOS devices can't play Akamai token protected streams through AirPlay on 1st, 2nd and 3rd Apple TV generations, which have an OS similar to iOS 8, or less.

### Environment information

* Library version: 3.0.1
* iOS / tvOS version: Any prior to iOS 11 and tvOS 11
* Device: Apple TV 1st, 2nd and 3rd Apple TV generations

### Reproducibility

Always reproducible

### Context

The `SRGAkamaiAssetResourceLoaderDelegate` is in charge of loading the Akamai token and add it to the master playlist request, to get it.

From years, all SRG SSR streams used only the Akamai MLS3 product, with the packaging included.
The delivered master playlist includes `#EXT-X-STREAM-INF` and `URI` for additional tracks (audios, subtitles) with full length urls.

Our implementation, named "download master playlist" implementation, supports iOS 9 to iOS 14, tvOS 9 to tvOS 14, on device and through AirPlay.

New LSVE SwissTXT streams uses Akamai MLS4 product, that does not include packaging.
The delivered master playlist from SRG encoders now includes `#EXT-X-STREAM-INF` and `URI` for additional tracks (audios, subtitles) with relative urls, relative from the master playlist url.

#6 issue explains why the "download master playlist" implementation does not work anymore with relative stream urls.
Decision was to drop iOS 9 and iOS 10 support.

SRF user feedbacks shared that it's also drop 1st, 2nd and 3rd Apple TV generations support, when playing with AirPlay.

### Steps to reproduce

1. Open a video in Play iOS app.
2. Cast to an Apple TV through AirPlay.

**Comment by pyby** [comment]
Those 1st, 2nd and 3rd Apple TV generations can't update their OS to tvOS 11 or more.

If we want to support it few more months, I suggest to mitigate between improvement for new LSVE stream did with #6.
- Restore a "download master playlist" implementation for "compatible" master playlist.
- Use iOS 11+ improvement otherwise.

A proposition implementation is available on `feature/resource-loader-all-tvOS`.

**Comment by pyby** [comment]
All UTs still passed on:
- iOS 14.2, iOS 13.5, iOS 12.2, iOS 11.4, iOS 10.3.1.
- tvOS 14.2, tvOS 13.4, tvOS 12.4.

**Comment by defagos** [comment]
Tested several medias with my iOS 14 devices, also over AirPlay on Apple TV 4K (tvOS 14.3). Works fine.
